apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: wellingtonex/backend-user:alpha
        ports:
        - containerPort: 3020
        env:
        - name: NODE_ENV
          value: "staging"
        - name: MONGO_URI
          value: "mongodb+srv://admin:admin@cluster0-ammhg.mongodb.net/test?retryWrites=true&w=majority"
        - name: SECRET_OR_KEY
          value: "chavemestre18"